### ISSUE TITLE
Not Found The requested URL

### ISSUE THREAD

**Issue by eArabic** [beardog108/seedbin#1]
Hello
Thank you very much for the wonderful script.
But it did not work I have, what the problem is and what the reason.
Please help the problem.

`Not Found
The requested URL /seedbin/index.htmlview.html was not found on this server.`

![323](https://cloud.githubusercontent.com/assets/24383546/22466879/5185dabe-e7d3-11e6-81f5-2138f26938ce.png)

**Comment by eArabic** [comment]
/seedbin/**# index.htmlview.html**

**Comment by beardog108** [comment]
Hey again @eArabic. I see you follow more than 1 of my projects.

This is actually a really new project of mine, and it's not really ready for use, but you're right about the issue you found. I'll fix it today.

**Comment by beardog108** [comment]
I believe I fixed it. Let me know if it doesn't work for you.

**Comment by eArabic** [comment]
Thank you very much, I am interested observer to you and everything based programming and writing ..
Is there anything new about a great project MicroTXT
And sorry for my poor English, 
I'm interested in what you are doing programming.
Thank you so much

**Comment by eArabic** [comment]
Now works Thank you very much

**Comment by beardog108** [comment]
For MicroTXT I am working on adding the tabs on the list of threads. I realize its taking a while, but i'm a college student & I also have other projects and information security stuff I work on.

I haven't forgotten about it though. I'll get some work done on it today and hopefully have something to show for it.

I appreciate your kind words and bug reports.

**Comment by eArabic** [comment]
Thank you very much for the speed of response, I am happy to meet you, and I wish you progress and prosperity in your studies and your life.
I'm still learning too, beginning in programming.
I would have liked, but I offer something new to programming and learning.
I do not know Do not be translated correctly, the translation by Google
So sorry for any error in the translation.
